version: '2'

services:
  elasticsearch:
    image: eeacms/elastic:7
    cap_add:
      - IPC_LOCK
    restart: always
    ports:
      - 9200:9200
    volumes:
      - elasticsearchDataDevMaster1:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - "discovery.type=single-node" 
      #pls, must match below!
      #
      - "kibana_system_password=KIBANAchangeme"
      - "elastic_password=SUPERUSER_PASSWORD"
      - "xpack.security.enabled=true"  

    networks:
      - esnet

  kibana:
    image: eeacms/elk-kibana:7
    restart: always
    ports:
      - "443:5601"
    volumes:
      - /backups:/backups
      - /etc/pki/tls/certs/server.crt:/ssl/server.crt:ro
      - /etc/pki/tls/private/server.key:/ssl/server.key:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      #pls, must match above!
      - ELASTICSEARCH_PASSWORD="KIBANAchangeme"
      - "xpack.security.enabled=true"
      - ELASTICSEARCH_URL="https://elasticsearch:9200"
      - ENABLE_SSL="YES"
    networks:
      - esnet
    depends_on:
      - "elasticsearch"

  sysctl:
    network_mode: none
    image: rawmind/alpine-sysctl:0.1
    privileged: true
    environment:
      - "SYSCTL_KEY=vm.max_map_count"
      - "SYSCTL_VALUE=262144"

volumes:
  elasticsearchDataDevMaster1:
    driver: local
  elasticsearchDataDevSlave1:
    driver: local
  configurationKibana:
    driver: local

networks:
  esnet:
    driver: bridge
